name: kitty
description: expenses app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  sqflite: ^2.2.2
  local_auth: ^2.1.3
  flutter_screen_lock: ^9.0.0+1
  page_transition: ^2.0.9
  equatable: ^2.0.5
  dotted_border: ^2.0.0+3
  collection: ^1.16.0
  pdf: ^3.8.4
  path_provider: ^2.0.11
  open_document: ^1.0.5
  flutter_secure_storage: ^7.0.1
  uuid: ^3.0.7
  easy_localization: ^3.0.1
  open_filex: ^4.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/icons/categories/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700